version: '3.8'

services:
  db:
    image: postgres:15
    container_name: agenda-postgres
    restart: always
    environment:
      POSTGRES_DB: agenda_db
      POSTGRES_USER: agenda_user
      POSTGRES_PASSWORD: agenda_pass
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: agenda-backend-app
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8082:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/agenda_db
      SPRING_DATASOURCE_USERNAME: agenda_user
      SPRING_DATASOURCE_PASSWORD: agenda_pass
      # Variables de Telegram (descomentar y configurar)
      # TELEGRAM_BOT_TOKEN: TU_TOKEN
      # TELEGRAM_CHAT_ID: TU_CHAT_ID

volumes:
  postgres_data:
